version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
      - api-network
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - api-network
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_RETENTION_HOURS=6
      - KAFKA_CFG_MAX_REQUEST_SIZE=10000000
    depends_on:
      - zookeeper
    networks:
      - api-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    volumes:
        - ./docker/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
        test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
        interval: 3s
        timeout: 3s
        retries: 10
    ports:
        - 9200:9200
    networks:
      - api-network
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    volumes:
        - ./docker/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
        elasticsearch:
            condition: service_healthy
    networks:
      - api-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.2
    depends_on:
        elasticsearch:
            condition: service_healthy
    volumes:
        - ./docker/filebeat.yml:/usr/share/filebeat/filebeat.yml
        - ./logs/:/logs/
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    depends_on:
        elasticsearch:
            condition: service_healthy
    healthcheck:
        test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
        interval: 3s
        timeout: 3s
        retries: 50
    ports:
        - 5601:5601
    networks:
      - api-network
networks: 
    api-network:
      driver: bridge
