package domain

type ExtratoDomain struct {
	Id                             string
	LimMaxCreditoPrivado           string
	LimMaxAtivosExterior           string
	LimMaxMesmoGestor              string
	AplicacaoMinima                string
	PodeCreditoprivado             string
	CotaDiaria                     string
	MetodoCalculoPerformance       string
	ClasseAnbima                   string
	FundoCnpj                      string
	Codominio                      string
	ContraparteLigado              string
	CotaValorEmissao               string
	CotaPatriminioLiquido          string
	DenominacaoSocial              string
	FormaDistribuicao              string
	DataCompetenciaDocumento       string
	TaxaDeIngresso                 string
	TaxaDePerformance              string
	TaxaDeSaida                    string
	FatorLimiteOperacoes           string
	FinalidadeOperacoesDerivativos string
	FundoCotas                     string
	FundoEspelho                   string
	InformacoesAdicionais          string
	PodeInvestirExterior           string
	NomeDoMercado                  string
	NegociacoesMercadoOrganizado   string
	PodeDerivativos                string
	PodeOperacoesSuperiorPl        string
	ParametroTaxaPerformance       string
	PoliticaInvistimento           string
	PrAcaoMax                      string
	PrAcaoMin                      string
	PrAdminGestorMax               string
	PrAdminGestorMin               string
	PrAtivoOutroMax                string
	PrAtivoOutroMin                string
	PrCiaMax                       string
	PrCiaMin                       string
	PrCompromMax                   string
	PrCompromMin                   string
	PrCotaEtfMax                   string
	PrCotaEtfMin                   string
	PrCotaFiMax                    string
	PrCotaFiMin                    string
	PrCotaFiProfMax                string
	PrCotaFiProfMin                string
	PrCotaFiQualifMax              string
	PrCotaFiQualifMin              string
	PrCotaFicMax                   string
	PrCotaFicMin                   string
	PrCotaFicProfMax               string
	PrCotaFicProfMin               string
	PrCotaFicQualifMax             string
	PrCotaFicQualifMin             string
	PrCotaFicfidcMax               string
	PrCotaFicfidcMin               string
	PrCotaFicfidcNpMax             string
	PrCotaFicfidcNpMin             string
	PrCotaFicfipMax                string
	PrCotaFicfipMin                string
	PrCotaFidcMax                  string
	PrCotaFidcMin                  string
	PrCotaFidcNpMax                string
	PrCotaFidcNpMin                string
	PrCotaFiiMax                   string
	PrCotaFiiMin                   string
	PrCotaFipMax                   string
	PrCotaFipMin                   string
	PrCotaFmieeMax                 string
	PrCotaFmieeMin                 string
	PrCriMax                       string
	PrCriMin                       string
	PrDebentureMax                 string
	PrDebentureMin                 string
	PrDerivMax                     string
	PrDerivMin                     string
	PrEmissorOutroMax              string
	PrEmissorOutroMin              string
	PrFiMax                        string
	PrFiMin                        string
	PrIndiceReferTaxaPerfm         string
	PrInstituicaoFinancMax         string
	PrInstituicaoFinancMin         string
	PrNpMax                        string
	PrNpMin                        string
	PrOuroMax                      string
	PrOuroMin                      string
	PrTitInstituicaoFinancBacenMax string
	PrTitInstituicaoFinancBacenMin string
	PrTitpubMax                    string
	PrTitpubMin                    string
	PrUniaoMax                     string
	PrUniaoMin                     string
	PrVlmobMax                     string
	PrVlmobMin                     string
	Prazo                          string
	PrazoAtualizCota               string
	PublicoAlvo                    string
	QtDiaConversaoCota             string
	PrUniaoMaxQtDiaPagtoCota       string
	PrUniaoMaxQtDiaPagtoResgate    string
	PrUniaoMaxQtDiaResgateCotas    string
	RegAnbima                      string
	ResultCartIncorpPl             string
	TaxaAdm                        string
	TaxaCustodiaMax                string
	TaxaIngressoPr                 string
	TaxaIngressoReal               string
	TaxaPerfm                      string
	TaxaSaidaPagtoResgate          string
	TaxaSaidaPr                    string
	TaxaSaidaReal                  string
	TpDiaPagtoResgate              string
	TpPrazo                        string
	VlCupom                        string
}
