package domain

type FundosDomain struct {
	Id                    string
	AdministradorNome     string
	AuditorNome           string
	CodigoCVM             string
	Classe                string
	ClasseAnbima          string
	AdministradorCNPJ     string
	AuditorCNPJ           string
	ControladorCNPJ       string
	CustodianteCNPJ       string
	FundoCNPJ             string
	Condominio            string
	Controlador           string
	GestorCPFCNPJ         string
	Custodiante           string
	FundoNome             string
	Diretor               string
	DataCancelamento      string
	DataConstituicao      string
	DataFim               string
	DataInicio            string
	DataInicioClasse      string
	DataInicioSocial      string
	DataInicioSituacao    string
	DataPatrimonioLiquido string
	DataRegistro          string
	Entidade              string
	CotasPossui           string
	Exclusivo             string
	GestorNome            string
	InformacoesAdicionais string
	InfoTaxaPerformance   string
	Exterior100           string
	PessoaFouPJ           string
	PublicoAlvo           string
	IndicadorDesempenho   string
	Situacao              string
	TaxaAdm               string
	TaxaPerformance       string
	TipoFundo             string
	TributacaoLongoPrazo  string
	ValorPatriminioLiq    string
}
