package domain

import "time"

type PerfilMensalDomain struct {
	Id                                string
	CenarioFPRCupom                   string
	CenarioFPRDolar                   string
	CenarioFPRIBOVESPA                string
	CenarioFPRJuros                   string
	CenarioFPROutro                   string
	CnpjFundo                         string
	ComitenteLigado1                  string
	ComitenteLigado2                  string
	ComitenteLigado3                  string
	CpfCnpjComitente1                 string
	CpfCnpjComitente2                 string
	CpfCnpjComitente3                 string
	CpfCnpjEmissor1                   string
	CpfCnpjEmissor2                   string
	CpfCnpjEmissor3                   string
	DelibAssemb                       string
	DenomSocial                       string
	DtComptc                          time.Time
	DtCotaTaxaPerfM                   time.Time
	EmissorLigado1                    string
	EmissorLigado2                    string
	EmissorLigado3                    string
	FatorRiscoNocional                string
	FatorRiscoOutro                   string
	Fpr                               string
	JustifVotoAdminAssemb             string
	ModVar                            string
	NrCotstBanco                      int
	NrCotstCapitaliz                  int
	NrCotstCorretoraDistrib           int
	NrCotstDistrib                    int
	NrCotstEapc                       int
	NrCotstEfpc                       int
	NrCotstEntidPrevidCompl           int
	NrCotstFiClube                    int
	NrCotstInvnr                      int
	NrCotstOutro                      int
	NrCotstPfPb                       int
	NrCotstPfVarejo                   int
	NrCotstPjFinanc                   int
	NrCotstPjNaoFinancPb              int
	NrCotstPjNaoFinancVarejo          int
	NrCotstRpps                       int
	NrCotstSegur                      int
	NrDiaCemPerc                      float64
	NrDiaCinquPerc                    float64
	PfPjComitente1                    string
	PfPjComitente2                    string
	PfPjComitente3                    string
	PfPjEmitter1                      string
	PfPjEmitter2                      string
	PfPjEmitter3                      string
	PrAtivoCredPriv                   float64
	PrAtivoEmitterLigado              float64
	PrColateralDeriv                  float64
	PrComitente1                      float64
	PrComitente2                      float64
	PrComitente3                      float64
	PrCotstEntidPrevidCompl           float64
	PrEmitter1                        float64
	PrEmitter2                        float64
	PrEmitter3                        float64
	PrPatrimLiqConvdCaixa             float64
	PrPatrimLiqMaiorCotst             float64
	PrPlCotstBanco                    float64
	PrPlCotstCapitaliz                float64
	PrPlCotstCorretoraDistrib         float64
	PrPlCotstDistrib                  float64
	PrPlCotstEapc                     float64
	PrPlCotstEfpc                     float64
	PrPlCotstFiClube                  float64
	PrPlCotstInvnr                    float64
	PrPlCotstOutro                    float64
	PrPlCotstPfPb                     float64
	PrPlCotstPfVarejo                 float64
	PrPlCotstPjFinanc                 float64
	PrPlCotstPjNaoFinancPb            float64
	PrPlCotstPjNaoFinancVarejo        float64
	PrPlCotstRpps                     float64
	PrPlCotstSegur                    float64
	PrVarCarteira                     float64
	PrVariacaoDiariaCota              float64
	PrVariacaoDiariaCotaEstresse      float64
	PrVariacaoDiariaOutro             float64
	PrVariacaoDiariaPlIbovespa        float64
	PrVariacaoDiariaPlTaxaAnual       float64
	PrVariacaoDiariaPlTaxaCambio      float64
	PrazoCarteiraTitulo               float64
	StLiquidez                        string
	VedacTaxaPerfm                    string
	Versao                            int
	VlContratoCompraDolar             float64
	VlContratoVendaDolar              float64
	VlCotaTaxaPerfm                   float64
	VlDireitoDistrib                  float64
	VlFatorRiscoNocionalLongCupom     float64
	VlFatorRiscoNocionalLongDolar     float64
	VlFatorRiscoNocionalLongIbovespa  float64
	VlFatorRiscoNocionalLongJuros     float64
	VlFatorRiscoNocionalLongOutro     float64
	VlFatorRiscoNocionalShortCupom    float64
	VlFatorRiscoNocionalShortDolar    float64
	VlFatorRiscoNocionalShortIbovespa float64
	VlFatorRiscoNocionalShortJuros    float64
	VlFatorRiscoNocionalShortOutro    float64
	VotoAdminAssemb                   string
}
