version: '3.7'

networks:
  api-network:
    external: true
    driver: bridge

services:
  api-fundos-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PARTITIONS=0,1,2,3,4
    networks: 
      - api-network
    volumes:
      - ./storage:/storage
      
  api-fundos-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PARTITIONS=5,6,7,8,9
    networks: 
      - api-network
    volumes:
      - ./storage:/storage
    
  api-fundos-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - PARTITIONS=10,11,12,13,14
    networks: 
      - api-network 
    volumes:
      - ./storage:/storage
    
  api-fundos-4:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - PARTITIONS=15,16,17,18,19
    networks: 
      - api-network
    volumes:
      - ./storage:/storage
