version: '3.7'

networks:
  api-network:
    external: true
    driver: bridge

services:
  api-fundos-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TOPICS=processar-arquivos
      - PARTITIONS=0,1,2,3,4,5,6
      - LOG_INFO_PATH=logs/api-fundos-info-1.log
      - LOG_ERROR_PATH=logs/api-fundos-error-1.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
      
  api-fundos-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - TOPICS=sincronizar,processar-arquivos
      - PARTITIONS=7,8,9,10,11,12
      - LOG_INFO_PATH=logs/api-fundos-info-2.log
      - LOG_ERROR_PATH=logs/api-fundos-error-2.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - TOPICS=processar-arquivos
      - PARTITIONS=13,14,15,16,17,18,19
      - LOG_INFO_PATH=logs/api-fundos-info-3.log
      - LOG_ERROR_PATH=logs/api-fundos-error-3.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network 
    
  api-fundos-4:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=0
      - LOG_INFO_PATH=logs/api-fundos-info-4.log
      - LOG_ERROR_PATH=logs/api-fundos-error-4.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-5:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=1
      - LOG_INFO_PATH=logs/api-fundos-info-5.log
      - LOG_ERROR_PATH=logs/api-fundos-error-5.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-6:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=2
      - LOG_INFO_PATH=logs/api-fundos-info-6.log
      - LOG_ERROR_PATH=logs/api-fundos-error-6.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-7:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=3
      - LOG_INFO_PATH=logs/api-fundos-info-7.log
      - LOG_ERROR_PATH=logs/api-fundos-error-7.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-8:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=4
      - LOG_INFO_PATH=logs/api-fundos-info-8.log
      - LOG_ERROR_PATH=logs/api-fundos-error-8.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-9:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=5
      - LOG_INFO_PATH=logs/api-fundos-info-9.log
      - LOG_ERROR_PATH=logs/api-fundos-error-9.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-10:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=6
      - LOG_INFO_PATH=logs/api-fundos-info-10.log
      - LOG_ERROR_PATH=logs/api-fundos-error-10.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-11:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=7
      - LOG_INFO_PATH=logs/api-fundos-info-11.log
      - LOG_ERROR_PATH=logs/api-fundos-error-11.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-12:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=8
      - LOG_INFO_PATH=logs/api-fundos-info-12.log
      - LOG_ERROR_PATH=logs/api-fundos-error-12.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-13:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8092:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=9
      - LOG_INFO_PATH=logs/api-fundos-info-13.log
      - LOG_ERROR_PATH=logs/api-fundos-error-13.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-14:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8093:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=10
      - LOG_INFO_PATH=logs/api-fundos-info-14.log
      - LOG_ERROR_PATH=logs/api-fundos-error-14.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-15:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8094:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=11
      - LOG_INFO_PATH=logs/api-fundos-info-15.log
      - LOG_ERROR_PATH=logs/api-fundos-error-15.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-16:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8095:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=12
      - LOG_INFO_PATH=logs/api-fundos-info-16.log
      - LOG_ERROR_PATH=logs/api-fundos-error-16.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-17:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8096:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=13
      - LOG_INFO_PATH=logs/api-fundos-info-17.log
      - LOG_ERROR_PATH=logs/api-fundos-error-17.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-18:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8097:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=14
      - LOG_INFO_PATH=logs/api-fundos-info-18.log
      - LOG_ERROR_PATH=logs/api-fundos-error-18.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-19:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8098:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=15
      - LOG_INFO_PATH=logs/api-fundos-info-19.log
      - LOG_ERROR_PATH=logs/api-fundos-error-19.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-20:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=16
      - LOG_INFO_PATH=logs/api-fundos-info-20.log
      - LOG_ERROR_PATH=logs/api-fundos-error-20.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-21:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100s:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=17
      - LOG_INFO_PATH=logs/api-fundos-info-21.log
      - LOG_ERROR_PATH=logs/api-fundos-error-21.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-22:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8101:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=18
      - LOG_INFO_PATH=logs/api-fundos-info-22.log
      - LOG_ERROR_PATH=logs/api-fundos-error-22.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-23:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8102:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=19
      - LOG_INFO_PATH=logs/api-fundos-info-23.log
      - LOG_ERROR_PATH=logs/api-fundos-error-23.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-24:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8103:8080"
    environment:
      - TOPICS=persistencia-dados
      - PARTITIONS=20
      - LOG_INFO_PATH=logs/api-fundos-info-24.log
      - LOG_ERROR_PATH=logs/api-fundos-error-24.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
