version: '3.7'

networks:
  api-network:
    external: true

volumes:
  compartilhado:

services:
  api-fundos-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PARTITIONS=0,1,2,3,4,
      - STORAGE=path/to/shared/directory/
    networks: 
      - api-network
    volumes:
      - compartilhado:/path/to/shared/directory
      
  api-fundos-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      - PARTITIONS=5,6,7,8,9
      - STORAGE=path/to/shared/directory/
    networks: 
      - api-network
    volumes:
      - compartilhado:/path/to/shared/directory
    
  api-fundos-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    restart: unless-stopped
    environment:
      - PARTITIONS=10,11,12,13,14
      - STORAGE=path/to/shared/directory/
    networks: 
      - api-network 
    volumes:
      - compartilhado:/path/to/shared/directory
    
  api-fundos-4:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    restart: unless-stopped
    environment:
      - PARTITIONS=15,16,17,18,19
      - STORAGE=path/to/shared/directory/
    networks: 
      - api-network
    volumes:
      - compartilhado:/path/to/shared/directory
