version: '3.7'

networks:
  api-network:
    external: true

volumes:
  elasticsearch:

services:
  api-fundos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks: 
      - api-network